version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - echo Start Deploy Lambda...
  build:
    commands:
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
       # update load forecast data
      - sam build -t sam-lambda-importforecastdata.yml
      - sam package --s3-bucket $SAM_Bucket --output-template-file importforecastdata.yml
      - sam deploy --force-upload true --template-file importforecastdata.yml --stack-name sam-lambda-loadforecastdata --capabilities CAPABILITY_NAMED_IAM --parameter-overrides  S3BucketName=$ForecastDemoDataBucket ImportDataCmdQARN=$ImportDataCmdQARN
     
  post_build:
    commands:
      - echo Build and deploy completed at `date`
